version: 2

project_name: newsletter-cli

before:
  hooks:
    - go mod tidy

builds:
  - id: newsletter-cli
    main: ./main.go
    binary: newsletter-cli
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - "-s -w -X main.version={{ .Version }}"
    flags:
      - -trimpath

archives:
  - id: default
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    wrap_in_directory: false
    formats: [tar.gz]
    files:
      - README.md
      - src: LICENSE*
        dst: LICENSE
    format_overrides:
      - goos: windows
        formats: [zip]

checksum:
  name_template: "checksums.txt"

dockers_v2:
  - id: newsletter-cli
    dockerfile: Dockerfile
    images:
      - "ghcr.io/loickal/newsletter-cli"
    tags:
      - "{{ .Version }}"
      - latest
    platforms:
      - linux/amd64
      - linux/arm64
    extra_files:
      - README.md
      - LICENSE
    labels:
      "org.opencontainers.image.title": "{{ .ProjectName }}"
      "org.opencontainers.image.version": "{{ .Version }}"
      "org.opencontainers.image.source": "{{ .GitURL }}"
    annotations:
      "org.opencontainers.image.description": "CLI tool to analyze and unsubscribe from newsletters"
    # removed the invalid --ulimit flag
    retry:
      attempts: 3
      delay: 10s
      max_delay: 1m

changelog:
  use: git
  sort: desc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'

release:
  github:
    owner: loickal
    name: newsletter-cli

# 📦 Winget Package Manager
winget:
  - name: newsletter-cli
    publisher: Loïc Kalbermatter
    publisher_url: https://github.com/loickal
    publisher_support_url: https://github.com/loickal/newsletter-cli/issues/new
    short_description: "A beautiful, privacy-friendly CLI tool to analyze and unsubscribe from newsletters."
    description: "A beautiful, privacy-friendly terminal tool to analyze and unsubscribe from newsletters — right from your inbox. Connects via IMAP, identifies newsletter senders, and provides an interactive TUI for management."
    homepage: "https://github.com/loickal/newsletter-cli"
    license: "MIT"
    license_url: "https://github.com/loickal/newsletter-cli/blob/main/LICENSE"
    package_identifier: Loickal.NewsletterCLI
    tags:
      - cli
      - newsletter
      - email
      - imap
      - golang
      - terminal
      - tui
    repository:
      owner: microsoft
      name: winget-pkgs
      branch: main
      token: "{{ .Env.WINGET_TOKEN }}"
      pull_request:
        enabled: true
        draft: false
    commit_author:
      name: "Loïc Kalbermatter"
      email: "loickal@users.noreply.github.com"

# 🍺 Modern Homebrew (Cask-based distribution)
homebrew_casks:
  - name: newsletter-cli
    directory: Casks
    url:
      verified: github.com/loickal/newsletter-cli
    homepage: "https://github.com/loickal/newsletter-cli"
    license: "MIT"
    description: "A beautiful, privacy-friendly CLI tool to analyze and unsubscribe from newsletters."
    repository:
      owner: loickal
      name: homebrew-newsletter-cli
      token: "{{ .Env.GITHUB_TOKEN }}"
    commit_author:
      name: "Loïc Kalbermatter"
      email: "loickal@users.noreply.github.com"
    hooks:
      post:
        install: |
          if OS.mac?
            system_command "/usr/bin/xattr",
              args: ["-dr", "com.apple.quarantine", "#{staged_path}/newsletter-cli"]
          end